jobs:
  verify:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Download Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./test/main

name: Run

on:
  schedule:
    - cron: "40 */6 * * *"
